spring:
  messages:
    fallback-to-system-locale: false

  r2dbc:
    url: r2dbc:h2:mem:///maindb
    pool:
      enabled: true
      min-idle: 1

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: jdbc:h2:mem:maindb;DB_CLOSE_DELAY=-1